# Site settings
title: ajaska's blog
email: ajaska@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Incoherent ramblings of a EECS major at Berkeley.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: ajaska
github_username: ajaska

# Build settings
markdown: kramdown
